-- White-label ecommerce settings reset.
-- Run this after importing schema.sql when you want a clean reusable baseline.
-- Database structure is unchanged; this only upserts configurable settings.

INSERT INTO site_settings (setting_key, setting_value, setting_type, setting_group) VALUES
('site_name', 'Your Store', 'text', 'general'),
('site_tagline', 'White-label ecommerce storefront', 'text', 'general'),
('site_description', 'A reusable ecommerce storefront ready for your brand.', 'textarea', 'seo'),
('site_url', '', 'text', 'general'),
('admin_url', '/admin/orders.php', 'text', 'general'),
('site_logo', '/logo.svg', 'image', 'general'),
('site_favicon', '/favicon.ico', 'image', 'general'),
('site_email', 'hello@example.com', 'text', 'general'),
('site_phone', '', 'text', 'general'),
('site_address', 'Configure store address in Admin Settings', 'textarea', 'general'),
('business_city', '', 'text', 'contact'),
('business_region', '', 'text', 'contact'),
('business_country', 'US', 'text', 'contact'),
('contact_email', 'hello@example.com', 'text', 'contact'),
('contact_address', 'Configure store address in Admin Settings', 'text', 'contact'),
('contact_hours', 'Mon-Fri: 9am-6pm', 'textarea', 'contact'),
('contact_map_embed', '', 'textarea', 'contact'),
('footer_about', 'A reusable ecommerce storefront. Update this copy in Admin Settings for each new brand.', 'textarea', 'footer'),
('footer_copyright', '© 2026 Your Store. All rights reserved.', 'text', 'footer'),
('newsletter_desc', 'Get product updates, offers, and store news straight to your inbox.', 'textarea', 'footer'),
('header_offer_text', 'Free delivery options can be configured in Admin Settings.', 'text', 'header'),
('payment_online_url', '', 'text', 'payments'),
('social_facebook', '', 'text', 'social'),
('social_instagram', '', 'text', 'social'),
('social_twitter', '', 'text', 'social'),
('social_youtube', '', 'text', 'social'),
('social_whatsapp', '', 'text', 'social'),
('shipping_free_above', '50', 'number', 'shipping'),
('shipping_charge', '5', 'number', 'shipping'),
('tax_percentage', '0', 'number', 'tax'),
('currency_symbol', '$', 'text', 'general'),
('currency_code', 'USD', 'text', 'general'),
('maintenance_mode', '0', 'boolean', 'general'),
('delivery_free_above', '50', 'number', 'delivery'),
('delivery_free_enabled', '1', 'boolean', 'delivery'),
('delivery_local_fee', '2.95', 'number', 'delivery'),
('delivery_standard_fee', '4.95', 'number', 'delivery'),
('delivery_small_order_min', '25', 'number', 'delivery'),
('delivery_small_order_fee', '1.50', 'number', 'delivery'),
('delivery_small_order_enabled', '1', 'boolean', 'delivery'),
('delivery_local_zone_label', 'Local delivery', 'text', 'delivery'),
('delivery_standard_zone_label', 'Standard delivery', 'text', 'delivery'),
('delivery_local_keywords', '', 'text', 'delivery'),
('delivery_local_postcode_prefixes', '', 'text', 'delivery'),
('google_analytics_id', '', 'text', 'seo'),
('meta_title', 'Your Store - Online Store', 'text', 'seo'),
('meta_description', 'Shop products online. Fast checkout, product management, customer management, and order management are ready to customize.', 'textarea', 'seo'),
('meta_keywords', 'online store, ecommerce, white label storefront', 'text', 'seo'),
('smtp_host', '', 'text', 'email'),
('smtp_port', '587', 'number', 'email'),
('smtp_encryption', 'tls', 'text', 'email'),
('smtp_username', '', 'text', 'email'),
('smtp_password', '', 'text', 'email'),
('smtp_from_email', 'hello@example.com', 'text', 'email'),
('smtp_from_name', 'Your Store', 'text', 'email'),
('admin_email', 'hello@example.com', 'text', 'email'),
('email_enabled', '1', 'boolean', 'email'),
('whatsapp_enabled', '0', 'boolean', 'email'),
('whatsapp_number', '', 'text', 'email'),
('whatsapp_api_key', '', 'text', 'email')
ON DUPLICATE KEY UPDATE
  setting_value = VALUES(setting_value),
  setting_type = VALUES(setting_type),
  setting_group = VALUES(setting_group);
